import OpenAI from "openai";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { isAuthorized } from "@/lib/auth";
import { campaignProfile, templateRules } from "@/lib/templates";
import { getWebsiteContext } from "@/lib/website";
import { getSupabase } from "@/lib/supabase";
export const runtime = "nodejs";
const leadSchema=z.object({name:z.string().trim().min(1).max(120),email:z.string().trim().email().max(320),company:z.string().trim().min(1).max(160),website:z.string().trim().url().optional().or(z.literal("")),linkedinUrl:z.string().trim().url().optional().or(z.literal("")),notes:z.string().trim().max(1500).optional()});
const outputSchema=z.object({status:z.enum(["queued","needs_review"]),template:z.enum(["website","automotive"]),reason:z.string(),verifiedDetail:z.string(),subject:z.string(),body:z.string()});
export async function POST(request:NextRequest){try{if(!isAuthorized(request))return NextResponse.json({error:"Unauthorized"},{status:401});if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"OPENAI_API_KEY is not configured."},{status:500});const {lead}=z.object({lead:leadSchema}).parse(await request.json());const websiteText=await getWebsiteContext(lead.website).catch(()=>"");const completion=await new OpenAI({apiKey:process.env.OPENAI_API_KEY}).responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",store:false,instructions:`You create accurate English outreach emails for Paras. Return the requested JSON only. ${templateRules}\nAutomatic quality gate: mark needs_review when no specific verified detail exists, a required fact is missing, or the email would include a generic unsupported observation. Do not use robotic, spammy, or hype language. Do not say you checked social profiles unless supplied data supports it.\nTemplate 1: subject “A few Meta Ads ideas for {{business_name}}”; mention one verified detail; introduce Paras and the Supremex India automotive-protection campaign; state exactly 186 leads from ₹16,157.82, averaging ₹86.87 per lead; include two meeting options.\nTemplate 2: subject “More PPF leads for {{business_name}}?”; only for verified automotive business plus city; ask whether to send 2–3 ideas.\nUse one template, clear paragraphs, and the supplied signature.`,input:JSON.stringify({lead,websiteText,profile:campaignProfile()}),text:{format:{type:"json_schema",name:"personalized_outreach",strict:true,schema:{type:"object",additionalProperties:false,properties:{status:{type:"string",enum:["queued","needs_review"]},template:{type:"string",enum:["website","automotive"]},reason:{type:"string"},verifiedDetail:{type:"string"},subject:{type:"string"},body:{type:"string"}},required:["status","template","reason","verifiedDetail","subject","body"]}}}});const draft=outputSchema.parse(JSON.parse(completion.output_text));if(draft.status==="queued"){const db=getSupabase();const {data:existing}=await db.from("email_queue").select("id").eq("recipient_email",lead.email).in("status",["pending","sending","sent"]).maybeSingle();if(!existing){const {error}=await db.from("email_queue").insert({recipient_name:lead.name,recipient_email:lead.email,company:lead.company,subject:draft.subject,email_body:draft.body,template_name:draft.template,verified_detail:draft.verifiedDetail,status:"pending"});if(error)throw error;}}return NextResponse.json({lead,draft,websiteAnalyzed:Boolean(websiteText)});}catch(error){console.error("Email generation failed",error);return NextResponse.json({error:error instanceof z.ZodError?"Invalid request.":"Unable to analyze this lead."},{status:500});}}
