"use client";

import Papa from "papaparse";
import { ChangeEvent, useState } from "react";

type Lead = { name: string; email: string; company: string; website?: string; linkedinUrl?: string; notes?: string; };
type DraftLead = Lead & { subject?: string; body?: string; approved: boolean; status: "ready" | "generating" | "generated" | "sending" | "sent" | "error"; error?: string; };
const inputClass = "w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";
function normaliseRow(row: Record<string, string>): Lead | null { const value = (key: string) => row[key] || row[key.toLowerCase()] || ""; const name=value("Name").trim(), email=value("Email").trim(), company=value("Company").trim(); if(!name||!email||!company)return null; return {name,email,company,website:value("Website").trim(),linkedinUrl:value("LinkedIn").trim()||value("LinkedIn URL").trim(),notes:value("Notes").trim()}; }
export default function Dashboard() {
  const [password,setPassword]=useState(""); const [senderName,setSenderName]=useState(""); const [senderCompany,setSenderCompany]=useState(""); const [offer,setOffer]=useState(""); const [callToAction,setCallToAction]=useState("Would a 15-minute chat next week be useful?"); const [leads,setLeads]=useState<DraftLead[]>([]); const [message,setMessage]=useState(""); const [manualLead,setManualLead]=useState<Lead>({name:"",email:"",company:"",website:"",linkedinUrl:"",notes:""});
  const headers={"Content-Type":"application/json","x-dashboard-password":password};
  function addLeads(newLeads:Lead[]){setLeads(c=>[...c,...newLeads.map(l=>({...l,approved:false,status:"ready" as const}))]);}
  function onCsvUpload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;Papa.parse<Record<string,string>>(file,{header:true,skipEmptyLines:true,complete:({data})=>{const valid=data.map(normaliseRow).filter((l):l is Lead=>Boolean(l));addLeads(valid);setMessage(`Imported ${valid.length} valid lead(s). CSV columns required: Name, Email, Company.`);},error:()=>setMessage("The CSV could not be read.")});event.target.value="";}
  function addManualLead(){if(!manualLead.name||!manualLead.email||!manualLead.company){setMessage("Name, email, and company are required.");return;}addLeads([manualLead]);setManualLead({name:"",email:"",company:"",website:"",linkedinUrl:"",notes:""});setMessage("Lead added.");}
  async function generate(index:number){if(!password||!senderName||!senderCompany||!offer||!callToAction){setMessage("Enter the dashboard password and all campaign details first.");return;}const lead=leads[index];setLeads(c=>c.map((x,i)=>i===index?{...x,status:"generating",error:undefined}:x));try{const response=await fetch("/api/generate",{method:"POST",headers,body:JSON.stringify({lead,senderName,senderCompany,offer,callToAction})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Generation failed.");setLeads(c=>c.map((x,i)=>i===index?{...x,subject:data.draft.subject,body:data.draft.body,status:data.draft.status==="queued"?"generated":"error",error:data.draft.status==="needs_review"?data.draft.reason:undefined}:x));}catch(error){setLeads(c=>c.map((x,i)=>i===index?{...x,status:"error",error:error instanceof Error?error.message:"Generation failed."}:x));}}
  async function generateAll(){for(let i=0;i<leads.length;i++)if(leads[i].status==="ready"||leads[i].status==="error")await generate(i);}
  return <main className="mx-auto max-w-6xl p-5 sm:p-10"><header className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">AI COLD EMAIL AGENT</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Review before you send.</h1></div><p className="max-w-md text-sm text-slate-600">Generate drafts, edit them in place, explicitly approve each one, and log successful sends to Supabase.</p></header>
  <section className="mb-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Campaign details</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={inputClass} type="password" placeholder="Dashboard password" value={password} onChange={e=>setPassword(e.target.value)}/><input className={inputClass} placeholder="Your name" value={senderName} onChange={e=>setSenderName(e.target.value)}/><input className={inputClass} placeholder="Your company" value={senderCompany} onChange={e=>setSenderCompany(e.target.value)}/><input className={inputClass} placeholder="Low-friction call to action" value={callToAction} onChange={e=>setCallToAction(e.target.value)}/></div><textarea className={`${inputClass} mt-3 min-h-20`} placeholder="What are you offering?" value={offer} onChange={e=>setOffer(e.target.value)}/></section>
  <section className="mb-5 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Upload CSV</h2><p className="mt-1 text-sm text-slate-600">Required headers: Name, Email, Company. Optional: Website, LinkedIn, Notes.</p><input className="mt-4 block text-sm" type="file" accept=".csv,text/csv" onChange={onCsvUpload}/></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Add one lead</h2><div className="mt-3 grid grid-cols-2 gap-2"><input className={inputClass} placeholder="Name" value={manualLead.name} onChange={e=>setManualLead({...manualLead,name:e.target.value})}/><input className={inputClass} placeholder="Company" value={manualLead.company} onChange={e=>setManualLead({...manualLead,company:e.target.value})}/><input className={`${inputClass} col-span-2`} placeholder="Email" value={manualLead.email} onChange={e=>setManualLead({...manualLead,email:e.target.value})}/></div><button className="mt-3 rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white" onClick={addManualLead}>Add lead</button></div></section>
  {message&&<p className="mb-4 text-sm text-slate-600">{message}</p>}<div className="mb-4 flex flex-wrap items-center gap-3"><button className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={!leads.length} onClick={generateAll}>Analyze and queue all</button><span className="text-sm text-slate-600">Quality-approved drafts enter the sending queue automatically; leads without verified details are held for review.</span></div>
  <section className="space-y-4">{leads.map((lead,index)=><article key={`${lead.email}-${index}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{lead.name} <span className="font-normal text-slate-500">· {lead.company}</span></h2><p className="text-sm text-slate-500">{lead.email}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium capitalize text-slate-700">{lead.status}</span></div>{lead.subject&&<div className="mt-4 space-y-2"><input className={inputClass} value={lead.subject} readOnly/><textarea className={`${inputClass} min-h-36`} value={lead.body} readOnly/><p className="text-sm text-slate-600">This draft is automatically queued only after the factual quality gate passes.</p></div>}<div className="mt-4 flex gap-2"><button className="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium disabled:opacity-50" disabled={lead.status==="generating"||lead.status==="sending"||lead.status==="sent"} onClick={()=>generate(index)}>{lead.subject?"Regenerate and requeue":"Analyze and queue"}</button></div>{lead.error&&<p className="mt-3 text-sm text-amber-700">{lead.error}</p>}</article>)}</section></main>;
}
